apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: go-sweenhez
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-sweenhez 
  name: go-sweenhez
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: go-sweenhez 
